name: cupertino_icons_module
description: "cupertino_icons juneflow module."
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/cupertino_icons_module

version: 1.0.0+2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  go_router: ^13.2.0
  cupertino_icons: ^1.0.6
  june_flow_util:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true